### PR TITLE
[BOOKAROOM-13] - Add Main Menu and Login 

### PR DESCRIPTION
**Pull request by srchang8**
Sprint 1
[BOOKAROOM-13]

Jira Link
https://bookaroom.atlassian.net/browse/BOOKAROOM-31

-Added Main Menu and Log In screens
-Added Segues

### CODE REVIEW

**Review by ricardocontrerasrobles — CHANGES_REQUESTED** [review]
Looks good. Let's add the constraints and code to avoid showing the Nav's Controller back button. It would be nice to add some screenshots to the description of the PR to see how the constraints handle different sizes like iPhon elandscape and iPad.

**Review by ricardocontrerasrobles — CHANGES_REQUESTED** [review]
Looks good. Let's add the constraints and code to avoid showing the Nav's Controller back button. It would be nice to add some screenshots to the description of the PR to see how the constraints handle different sizes like iPhone landscape and iPad.

**Comment by ricardocontrerasrobles** [comment]
Sorry for the double comments. My internet connection was unstable.

**Comment by srchang8** [comment]
Ok i added the constraints, removed the back button on the navigation controller bar and made it translucent.

I committed the changes and pushed it to my repository. Should i make a new pull request?

here are some of the screen shots i took on different devices and landscapes. 

Iphone 6
image
image


Ipad air
image
image

Iphone SE
image
image

**Comment by srchang8** [comment]
oops, they were suppose to be links. sorry for the sizing

**Review by ricardocontrerasrobles — APPROVED** [review]
Looks good

**Pull request merged**
